feat: 2.7.0
asyncapi/jasyncapi-idea-plugin pull request #141
Opened 2024-12-03 10:14 UTC by Pakisan

### Added

- Resolve local references for correct AsyncAPI specification rendering

### Fixed

- Inject AsyncAPI specification directly into preview instead of saving as temporal file and rendering it

2024-12-09 18:58 UTC, philCryoport commented
Noting for the record the following errors and warnings occurred with `./gradlew :buildPlugin`:
```
> Task :verifyPluginProjectConfiguration
[org.jetbrains.intellij.platform] The following plugin configuration issues were found:
- The dependency on the Kotlin Standard Library (stdlib) is automatically added when using the Gradle Kotlin plugin and may conflict with the version provided with the IntelliJ Platform, see: https://jb.gg/intellij-platform-kotlin-stdlib

> Task :buildSearchableOptions
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
java.lang.Error: no ComponentUI class for: com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.updateUI(ComboBoxAction.java:372)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:152)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1.<init>(PerFileConfigurableBase.java:882)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction.createComboBoxButton(PerFileConfigurableBase.java:882)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:86)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:614)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:606)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:600)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createDefaultMappingComponent(PerFileConfigurableBase.java:222)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createComponent(PerFileConfigurableBase.java:181)
        at com.intellij.openapi.vfs.encoding.FileEncodingConfigurable.createComponent(FileEncodingConfigurable.java:159)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:169)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide.ui.search.TraverseUIStarter.lambda$startup$0(TraverseUIStarter.java:120)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
java.lang.Error: no ComponentUI class for: com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.updateUI(ComboBoxAction.java:372)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:152)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1.<init>(PerFileConfigurableBase.java:882)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction.createComboBoxButton(PerFileConfigurableBase.java:882)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:86)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:614)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:606)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:600)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createDefaultMappingComponent(PerFileConfigurableBase.java:222)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createComponent(PerFileConfigurableBase.java:181)
        at com.intellij.openapi.vfs.encoding.FileEncodingConfigurable.createComponent(FileEncodingConfigurable.java:159)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:169)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide. [...]

2024-12-09 19:00 UTC, philCryoport commented
[Gradle Wrapper version needs to be updated to 8.11.1](https://gradle.org/releases/)

```
./gradlew --version
------------------------------------------------------------
Gradle 8.10
------------------------------------------------------------

Build time:    2024-08-14 11:07:45 UTC
Revision:      fef2edbed8af1022cefaf44d4c0514c5f89d7b78

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.4 (Eclipse Adoptium 21.0.4+7-LTS)
```

2024-12-09 21:07 UTC, Pakisan commented
> [Gradle Wrapper version needs to be updated to 8.11.1](https://gradle.org/releases/)
> 
> ```
> ./gradlew --version
> ------------------------------------------------------------
> Gradle 8.10
> ------------------------------------------------------------
> 
> Build time:    2024-08-14 11:07:45 UTC
> Revision:      fef2edbed8af1022cefaf44d4c0514c5f89d7b78
> 
> Kotlin:        1.9.24
> Groovy:        3.0.22
> Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
> Launcher JVM:  21.0.4 (Eclipse Adoptium 21.0.4+7-LTS)
> ```

Done

2024-12-10 21:19 UTC, philCryoport requested changes
Comments on code

2024-12-11 00:31 UTC, philCryoport commented
Do we need to add tests in `/src/test/kotlin/com.asyncapi.plugin.idea/`?

2024-12-11 00:46 UTC, philCryoport commented
`./gradlew :verifyPlugin` passes, although with warnings:

```
jasyncapi-idea-plugin on  release/2.7.0 [$] is 📦 2.7.0+jre17 via ☕ v21.0.4 via 🅒 base took 2m 29.6s
➜ ./gradlew :verifyPlugin

> Task :initializeIntellijPlatformPlugin
[org.jetbrains.intellij.platform] IntelliJ Platform Gradle Plugin is outdated: 2.1.0. Update `org.jetbrains.intellij.platform` to: 2.2.0

> Task :verifyPlugin
Starting the IntelliJ Plugin Verifier 1.381
2024-12-10T15:16:37 [main] INFO  c.j.p.options.OptionsParser - The verification directory /Users/pschlesinger/GitHub/asyncapi/jasyncapi-idea-plugin/build/reports/pluginVerifier is being deleted because it is not empty.
Verification reports directory: /Users/pschlesinger/GitHub/asyncapi/jasyncapi-idea-plugin/build/reports/pluginVerifier
2024-12-10T15:16:38 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/930557bef863f2691286b5cffbd1b3eb/transformed/ideaIC-2022.3-aarch64
2024-12-10T15:16:38 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/930557bef863f2691286b5cffbd1b3eb/transformed/ideaIC-2022.3-aarch64
2024-12-10T15:16:38 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:38 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2022300] and the plugin version [223.7571.182] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:41 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/86639b8551d8c5664d950e2341f84b5e/transformed/ideaIC-2022.3.1-aarch64
2024-12-10T15:16:41 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/86639b8551d8c5664d950e2341f84b5e/transformed/ideaIC-2022.3.1-aarch64
2024-12-10T15:16:41 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:41 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2022300] and the plugin version [223.8214.52] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:43 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/c50a5d2ee84176a524f88ca039e0545e/transformed/ideaIC-2022.3.2-aarch64
2024-12-10T15:16:43 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/c50a5d2ee84176a524f88ca039e0545e/transformed/ideaIC-2022.3.2-aarch64
2024-12-10T15:16:43 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:44 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2022300] and the plugin version [223.8617.56] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:47 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/edff67157752c7fc0f11450cb0a1b3c6/transformed/ideaIC-2022.3.3-aarch64
2024-12-10T15:16:47 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/edff67157752c7fc0f11450cb0a1b3c6/transformed/ideaIC-2022.3.3-aarch64
2024-12-10T15:16:47 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:47 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2022300] and the plugin version [223.8836.41] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:49 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/c62d66f98fd74a9aed00186c13f01639/transformed/ideaIC-2023.1-aarch64
2024-12-10T15:16:49 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/c62d66f98fd74a9aed00186c13f01639/transformed/ideaIC-2023.1-aarch64
2024-12-10T15:16:49 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:49 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2023100] and the plugin version [231.8109.175] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:51 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/59189c502667b6c1cdf53869b627827a/transformed/ideaIC-2023.1.1-aarch64
2024-12-10T15:16:51 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/59189c502667b6c1cdf53869b627827a/transformed/ideaIC-2023.1.1-aarch64
2024-12-10T15:16:51 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:52 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2023100] and the plugin version [231.8770.65] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
2024-12-10T15:16:54 [main] INFO  verification - Reading IDE /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5dfe475b51348dd737f83c53b889e909/transformed/ideaIC-2023.1.2-aarch64
2024-12-10T15:16:54 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5dfe475b51348dd737f83c53b889e909/transformed/ideaIC-2023.1.2-aarch64
2024-12-10T15:16:54 [main] INFO  c.j.p.options.OptionsParser - Using Java runtime from /Users/pschlesinger/.gradle/caches/8.11.1/transforms/5a14aba31bb5a6326863e391d684d34e/transformed/jbr-jbr_jcef-17.0.5-osx-aarch64-b653.14/jbr_jcef-17.0.5-osx-aarch64-b653.14/Contents/Home
2024-12-10T15:16:55 [main] WARN  c.j.p.structure.ide.IdeManagerImpl - Failed to read bundled plugin 'plugins/cwm-plugin': Plugin 'plugins/cwm-plugin' is invalid: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [2023100] and the plugin version [231.9011.34] shoul [...]

2024-12-11 13:57 UTC, Pakisan commented on build.gradle.kts
> +version = "2.7.0+jre17"
+jre17 is a valid version of jdk

I fixed typos in CHANGELOG.md

2024-12-11 13:58 UTC, Pakisan commented on CHANGELOG.md
> +- [GitHub](https://github.com/asyncapi/jasyncapi-idea-plugin/releases/new?tag=2.7.0%2Bjre17)
Fixed. jre17 is valid tag

2024-12-11 14:01 UTC, Pakisan commented on build.gradle.kts
>              ))
2024.2.5 is a last version of IDEA for v2

2024.3 is supporting by v3 - https://github.com/asyncapi/jasyncapi-idea-plugin/tree/release/3.0.0

2024-12-13 02:11 UTC, philCryoport requested changes
Two things:
1) `COMPATIBILITY.md` apparently hasn't been updated since version `2.2.0`

2) I can't figure out how to run the code tests.  

If I run `./gradlew check --scan`, it fails complaining that `org.junit.vintage:junit-vintage-engine` depends on a too-old version of `junit`.

Same result if I try within IntelliJ IDEA to run a single test -- say AsyncAPIJsonSchemaProviderTest's `test - injects correctly` test -- same error

If I comment-out that `vintage` line in `build.gradle.kts` -- and then run `./gradlew check --scan`...ZERO tests are run.

If now -- with the `vintage` line commented-out -- I try within IntelliJ IDEA to run a single test -- say AsyncAPIJsonSchemaProviderTest's `test - injects correctly` test -- it complains:
```
No matching tests found in any candidate test task.
    Requested tests:
        Test pattern com.asyncapi.plugin.idea._core.AsyncAPIJsonSchemaProviderTest.test - injects correctly in task :test
```

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/76657de7-a0c6-416d-955e-ad8f0c43c9b5" />

What am I doing wrong?

2025-05-15 10:56 UTC, Pakisan commented
@philCryoport please re-check

Tests were reanimated and COMPATABILITY.md was updated

2025-05-19 12:10 UTC, merged