WIP: chore: update for Intellij 2023.1
asyncapi/jasyncapi-idea-plugin pull request #27
Opened 2023-04-21 09:09 UTC by nexoscp

Update for Intellij 2023.1

2023-04-21 21:50 UTC, Pakisan commented
@nexoscp hi!

I didn't merge [release/2.0.0](https://github.com/asyncapi/jasyncapi-idea-plugin/tree/release/2.0.0) into `master`, that's why you have conflicts. Please re-target your mr to branch, which I created for you - `release/2.1.0`

2023-04-21 21:58 UTC, Pakisan requested changes

2023-04-21 21:58 UTC, Pakisan commented on build.gradle.kts
> +version = "2.0.1+jre17"
It's new feature, not bug fix. Please change to `2.1.0`

2023-04-21 21:58 UTC, Pakisan commented on build.gradle.kts
> +    sinceBuild.set("231")
If you replace `223` with `231`, users on 2022.3.* will not receive any new updates.

Did you find some compatibility problems?

2023-04-21 21:58 UTC, Pakisan commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-rc-1-bin.zip
New version of gradle is out. I propose to you to change this RC version to stable one - 8.1.1

2023-04-27 21:53 UTC, alvesf2 commented
Hello everybody. Do you have any estimation of when this will be in production?
Cheers!

2023-05-01 22:43 UTC, Pakisan approved these changes

2023-05-01 22:46 UTC, merged

2023-05-01 22:49 UTC, Pakisan commented
> Hello everybody. Do you have any estimation of when this will be in production?
> 
> Also, <img alt="image" width="400" src="https://user-images.githubusercontent.com/72494699/234999770-3eb1ab3a-3fd2-42e8-a7e6-53905f4522e5.png"> These links take us to the old repository (https://github.com/Pakisan/jasyncapi-idea-plugin), not this one. It would be nice to update this.
> 
> Apologies for commenting on the PR, but seems like there isn't an issue open to track this work.
> 
> Cheers! 🙇

Hi @alvesf2 

I Will make the proposed changes, by myself, run check compatibility tests, and send them to review today evening(02.05)

2023-05-06 11:14 UTC, alvesf2 commented
> > Hello everybody. Do you have any estimation of when this will be in production?
> > Also, <img alt="image" width="400" src="https://user-images.githubusercontent.com/72494699/234999770-3eb1ab3a-3fd2-42e8-a7e6-53905f4522e5.png"> These links take us to the old repository (https://github.com/Pakisan/jasyncapi-idea-plugin), not this one. It would be nice to update this.
> > Apologies for commenting on the PR, but seems like there isn't an issue open to track this work.
> > Cheers! 🙇
> 
> Hi @alvesf2
> 
> I Will make the proposed changes, by myself, run check compatibility tests, and send them to review today evening(02.05)

Hi, again @Pakisan Usually how long does it take for IntelliJ to validate this change?

Thank you,
Fábio

2023-05-09 01:12 UTC, Pakisan commented
> > > Hello everybody. Do you have any estimation of when this will be in production?
> > > Also, <img alt="image" width="400" src="https://user-images.githubusercontent.com/72494699/234999770-3eb1ab3a-3fd2-42e8-a7e6-53905f4522e5.png"> These links take us to the old repository (https://github.com/Pakisan/jasyncapi-idea-plugin), not this one. It would be nice to update this.
> > > Apologies for commenting on the PR, but seems like there isn't an issue open to track this work.
> > > Cheers! 🙇
> > 
> > 
> > Hi @alvesf2
> > I Will make the proposed changes, by myself, run check compatibility tests, and send them to review today evening(02.05)
> 
> Hi, again @Pakisan Usually how long does it take for IntelliJ to validate these changes?
> 
> Thank you, Fábio

Hi!

> The review may take up to two business days (Monday - Friday, CET timezone, excluding official holidays). You will get a response on the Email used to register in the Marketplace. If you have any questions or feedback, please reach out to the Support team at

I missed with release channel. Re-targeted release to stable now.

You can download the plugin and install it manually from the release page. I pushed all changes to the release branch and attached `.jar`, `.zip`

2023-05-09 19:32 UTC, Pakisan commented
> > > Hello everybody. Do you have any estimation of when this will be in production?
> > > Also, <img alt="image" width="400" src="https://user-images.githubusercontent.com/72494699/234999770-3eb1ab3a-3fd2-42e8-a7e6-53905f4522e5.png"> These links take us to the old repository (https://github.com/Pakisan/jasyncapi-idea-plugin), not this one. It would be nice to update this.
> > > Apologies for commenting on the PR, but seems like there isn't an issue open to track this work.
> > > Cheers! 🙇
> > 
> > 
> > Hi @alvesf2
> > I Will make the proposed changes, by myself, run check compatibility tests, and send them to review today evening(02.05)
> 
> Hi, again @Pakisan Usually how long does it take for IntelliJ to validate these changes?
> 
> Thank you, Fábio

Release was approved and available now